In [1]:
import numpy as np

In [2]:
def is_problem_safe(numbers: np.ndarray) -> bool:
    diff = np.diff(numbers)
    return all(diff > 0) and all(diff <= 3) or all(diff < 0) and all(diff >= -3)

In [3]:
a = np.array(
    [
        1,
        3,
        2,
        4,
        5,
        6,
        7,
    ]
)
for i in range(len(a)):
    small_a = np.delete(a, i)

    print(small_a, is_problem_safe(small_a))

[3 2 4 5 6 7] False
[1 2 4 5 6 7] True
[1 3 4 5 6 7] True
[1 3 2 5 6 7] False
[1 3 2 4 6 7] False
[1 3 2 4 5 7] False
[1 3 2 4 5 6] False


In [4]:
page = [1, 2, 3, 4, 5]
for i, p in enumerate(page[::-1]):
    print(p, page[: len(page) - i - 1])

5 [1, 2, 3, 4]
4 [1, 2, 3]
3 [1, 2]
2 [1]
1 []


In [7]:
from itertools import combinations_with_replacement, permutations

all_operations = []
all_combinations = list(combinations_with_replacement("+*", 4))
for c in all_combinations:
    all_operations.extend(set(permutations(c)))
all_operations

[('+', '+', '+', '+'),
 ('+', '+', '*', '+'),
 ('+', '+', '+', '*'),
 ('*', '+', '+', '+'),
 ('+', '*', '+', '+'),
 ('+', '*', '+', '*'),
 ('*', '+', '*', '+'),
 ('*', '+', '+', '*'),
 ('+', '+', '*', '*'),
 ('*', '*', '+', '+'),
 ('+', '*', '*', '+'),
 ('*', '*', '+', '*'),
 ('*', '+', '*', '*'),
 ('+', '*', '*', '*'),
 ('*', '*', '*', '+'),
 ('*', '*', '*', '*')]