In [2]:
import numpy as np

In [5]:
def is_problem_safe(numbers: np.ndarray) -> bool:
    diff = np.diff(numbers)
    return all(diff > 0) and all(diff <= 3) or all(diff < 0) and all(diff >= -3)

In [11]:
a = np.array(
    [
        1,
        3,
        2,
        4,
        5,
        6,
        7,
    ]
)
for i in range(len(a)):
    small_a = np.delete(a, i)

    print(small_a, is_problem_safe(small_a))

[3 2 4 5 6 7] False
[1 2 4 5 6 7] True
[1 3 4 5 6 7] True
[1 3 2 5 6 7] False
[1 3 2 4 6 7] False
[1 3 2 4 5 7] False
[1 3 2 4 5 6] False
